Repository ssu-capstone2-DeunDeun/DeunDeun-backend, pull requests merged in 2021-06, with the labels that each got.

#75 [REFACTOR]: 댓글 생성, 수정, 삭제 로직 (#72)
  src/main/java/kr/co/deundeun/groopy/controller/comment/CommentController.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApply/ClubApply.java
  src/main/java/kr/co/deundeun/groopy/domain/clubRecruit/ClubRecruit.java
  src/main/java/kr/co/deundeun/groopy/domain/comment/Comment.java
  src/main/java/kr/co/deundeun/groopy/domain/post/Post.java
  src/main/java/kr/co/deundeun/groopy/dto/comment/CommentRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/comment/CommentResponseDto.java
  src/main/java/kr/co/deundeun/groopy/helper/CommentHelper.java
  src/main/java/kr/co/deundeun/groopy/service/CommentService.java
Labels: backend, feature, refactor

#79 [FIX]: 유저의 지원 취소
  src/main/java/kr/co/deundeun/groopy/domain/clubApply/ClubApply.java
  src/main/java/kr/co/deundeun/groopy/service/ClubApplyService.java
Labels: backend, fix

#81 [FEAT]: 메시지 보내기, 네이버 로그인 추가
  src/main/java/kr/co/deundeun/groopy/config/AppConfig.java
  src/main/java/kr/co/deundeun/groopy/config/SmsProperties.java
  src/main/java/kr/co/deundeun/groopy/config/security/oauth2/CustomOAuth2UserService.java
  src/main/java/kr/co/deundeun/groopy/config/security/oauth2/GoogleOAuth2UserInfo.java
  src/main/java/kr/co/deundeun/groopy/config/security/oauth2/NaverOAuth2UserInfo.java
  src/main/java/kr/co/deundeun/groopy/config/security/oauth2/OAuth2UserInfo.java
  src/main/java/kr/co/deundeun/groopy/config/security/oauth2/OAuth2UserInfoFactory.java
  src/main/java/kr/co/deundeun/groopy/controller/message/MessageController.java
  src/main/java/kr/co/deundeun/groopy/domain/user/User.java
  src/main/java/kr/co/deundeun/groopy/dto/message/ContentType.java
  src/main/java/kr/co/deundeun/groopy/dto/message/Message.java
  src/main/java/kr/co/deundeun/groopy/dto/message/MessageRequest.java
  src/main/java/kr/co/deundeun/groopy/dto/message/MessageType.java
  src/main/java/kr/co/deundeun/groopy/dto/message/SmsRequestDto.java
  src/main/java/kr/co/deundeun/groopy/service/MessageService.java
  src/main/resources/application.yml
Labels: backend, feature

#85 ClubRecruit 리팩토링
  src/main/java/kr/co/deundeun/groopy/domain/clubApplyForm/ClubApplyForm.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApplyForm/ClubRecruitQuestion.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApplyForm/MultipleChoice.java
  src/main/java/kr/co/deundeun/groopy/domain/clubRecruit/ClubRecruit.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApplyForm/ApplyFormRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApplyForm/MultipleChoiceRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApplyForm/RecruitQuestionRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubRecruit/ClubRecruitRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubRecruit/ClubRecruitResponseDto.java
  src/main/java/kr/co/deundeun/groopy/service/ClubApplyFormService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubRecruitService.java
Labels: backend, refactor

#86 DeunDeun-backend-74 로그 작업
  build.gradle
  src/main/java/kr/co/deundeun/groopy/common/advice/LoggerAdvice.java
  src/main/java/kr/co/deundeun/groopy/common/aspect/LoggerAspect.java
  src/main/java/kr/co/deundeun/groopy/common/dto/ErrorResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/alarm/AlarmRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/alarm/AlarmResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/club/ClubRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/club/ClubResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApply/ApplyQAResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApply/ApplyRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApply/ApplyResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApply/ApplySummaryResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApplyForm/ApplyFormRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApplyForm/ApplyFormResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApplyForm/MultipleChoiceRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApplyForm/MultipleChoiceResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApplyForm/RecruitQuestionRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApplyForm/RecruitQuestionResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubPosition/ClubPositionRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubPosition/ClubPositionResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubPosition/participates/PositionChangeDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubRecruit/ClubRecruitRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubRecruit/ClubRecruitResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/comment/CommentRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/comment/CommentResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/common/jwt/JwtRefreshResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/common/mail/MailRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/common/page/PageRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/evaluate/ClubApplyStatusDto.java
  src/main/java/kr/co/deundeun/groopy/dto/evaluate/EvaluateRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/evaluate/EvaluateResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/hashtag/HashtagResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/home/ClubByCategoryDto.java
  src/main/java/kr/co/deundeun/groopy/dto/home/HomeResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/home/PopularClubDto.java
  src/main/java/kr/co/deundeun/groopy/dto/home/PopularPostDto.java
  src/main/java/kr/co/deundeun/groopy/dto/home/RecruitingClubDto.java
  src/main/java/kr/co/deundeun/groopy/dto/like/LikeResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/like/liked/LikeListResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/message/MessageRequest.java
  src/main/java/kr/co/deundeun/groopy/dto/message/SmsRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/participate/ParticipateRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/participate/ParticipateResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/post/PostRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/post/PostResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/user/UserRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/user/UserResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/user/userClub/UserClubDto.java
  src/main/resources/logback-spring.xml
Labels: backend, feature

#91 Deun deun backend 82
  LICENSE
  README.md
  src/main/java/kr/co/deundeun/groopy/common/advice/ExceptionAdvice.java
  src/main/java/kr/co/deundeun/groopy/config/AppConfig.java
  src/main/java/kr/co/deundeun/groopy/config/security/GroupInterceptor.java
  src/main/java/kr/co/deundeun/groopy/controller/message/MessageController.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubRecruitRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/PostRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApplyForm/ClubRecruitQuestion.java
  src/main/java/kr/co/deundeun/groopy/domain/clubRecruit/ClubRecruit.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApplyForm/RecruitQuestionRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubApplyForm/RecruitQuestionResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubRecruit/ClubRecruitRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubRecruit/ClubRecruitResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/common/mail/MailRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/message/MessageRequest.java
  src/main/java/kr/co/deundeun/groopy/dto/post/PostResponseDto.java
  src/main/java/kr/co/deundeun/groopy/service/ClubApplyFormService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubRecruitService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubService.java
  src/main/java/kr/co/deundeun/groopy/service/CommentService.java
  src/main/java/kr/co/deundeun/groopy/service/MailService.java
  src/main/java/kr/co/deundeun/groopy/service/PostService.java
  src/main/java/kr/co/deundeun/groopy/util/Scheduler.java
Labels: backend, feature, fix
