Repository ssu-capstone2-DeunDeun/DeunDeun-backend, pull requests merged in 2021-05, with the labels that each got.

#13 [DOCS]: User 테스트 API 추가
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/kr/co/deundeun/groopy/controller/hashtag/dto/HashtagRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/hashtag/dto/HashtagResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/user/UserController.java
  src/main/java/kr/co/deundeun/groopy/controller/user/dto/HashtagRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/user/dto/UserResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dao/UserHashtagRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/UserRepository.java
  src/main/java/kr/co/deundeun/groopy/service/HashtagService.java
  src/main/java/kr/co/deundeun/groopy/service/UserService.java
  src/test/java/kr/co/deundeun/groopy/controller/docs/UserDocumentation.java
  src/test/java/kr/co/deundeun/groopy/controller/user/UserControllerTest.java
Labels: docs

#18 DeunDeun-backend-14 모집 공고 전체보기
  src/main/java/kr/co/deundeun/groopy/controller/clubRecruit/ClubRecruitController.java
  src/main/java/kr/co/deundeun/groopy/controller/clubRecruit/dto/RecruitResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubRecruit/dto/RecruitSummaryResponseDto.java
  src/main/java/kr/co/deundeun/groopy/service/ClubRecruitService.java
  src/test/java/kr/co/deundeun/groopy/config/DocumentationWithSecurity.java
  src/test/java/kr/co/deundeun/groopy/config/SecurityDocumentationConfig.java
  src/test/java/kr/co/deundeun/groopy/controller/clubRecruit/ClubRecruitControllerTest.java
  src/test/java/kr/co/deundeun/groopy/controller/clubRecruit/ClubRecruitDocumentation.java
  src/test/java/kr/co/deundeun/groopy/controller/user/UserControllerTest.java
  src/test/java/kr/co/deundeun/groopy/controller/user/UserDocumentation.java
Labels: backend, feature

#20 [FEAT]: 이미지 업로드(#15)
  src/main/java/kr/co/deundeun/groopy/controller/image/ImageController.java
  src/main/java/kr/co/deundeun/groopy/controller/testController.java
  src/main/java/kr/co/deundeun/groopy/util/S3Uploader.java
Labels: backend, feature

#25 [FEAT]: jwt ACC/REF 토큰 발급(#16)
  src/main/java/kr/co/deundeun/groopy/GroopyApplication.java
  src/main/java/kr/co/deundeun/groopy/config/AppProperties.java
  src/main/java/kr/co/deundeun/groopy/config/security/CustomUserDetailsService.java
  src/main/java/kr/co/deundeun/groopy/config/security/JwtTokenProvider.java
  src/main/java/kr/co/deundeun/groopy/config/security/TokenAuthenticationFilter.java
  src/main/java/kr/co/deundeun/groopy/config/security/oauth2/CustomOAuth2UserService.java
  src/main/java/kr/co/deundeun/groopy/config/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/co/deundeun/groopy/config/security/oauth2/OAuth2UserInfoFactory.java
  src/main/java/kr/co/deundeun/groopy/dao/UserRepository.java
  src/main/java/kr/co/deundeun/groopy/helper/UserHelper.java
  src/main/java/kr/co/deundeun/groopy/service/UserService.java
Labels: backend, feature

#24 DeunDeun-backend-19 동아리 상세 첫 화면
  src/main/java/kr/co/deundeun/groopy/config/security/GroupInterceptor.java
  src/main/java/kr/co/deundeun/groopy/config/security/UserPrincipal.java
  src/main/java/kr/co/deundeun/groopy/controller/club/ClubController.java
  src/main/java/kr/co/deundeun/groopy/controller/club/dto/ClubRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/club/dto/ClubResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubRecruit/dto/RecruitResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/post/dto/PostResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubImageRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubRecruitRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/PostRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/club/Club.java
  src/main/java/kr/co/deundeun/groopy/domain/image/ClubImage.java
  src/main/java/kr/co/deundeun/groopy/domain/image/Image.java
  src/main/java/kr/co/deundeun/groopy/domain/post/Post.java
  src/main/java/kr/co/deundeun/groopy/exception/NameDuplicateException.java
  src/main/java/kr/co/deundeun/groopy/service/ClubService.java
  src/test/java/kr/co/deundeun/groopy/controller/user/UserControllerTest.java
Labels: backend, feature

#26 [FEAT]: JWT_AccessToken 재발급(#17)
  src/main/java/kr/co/deundeun/groopy/config/SecurityConfig.java
  src/main/java/kr/co/deundeun/groopy/config/security/JwtTokenProvider.java
  src/main/java/kr/co/deundeun/groopy/controller/jwt/JwtController.java
  src/main/java/kr/co/deundeun/groopy/controller/jwt/dto/JwtRefreshResponseDto.java
  src/main/java/kr/co/deundeun/groopy/service/JwtService.java
Labels: backend, feature

#27 Deun-deun-backend-23 동아리 좋아요
  src/main/java/kr/co/deundeun/groopy/common/ErrorCode.java
  src/main/java/kr/co/deundeun/groopy/common/advice/ExceptionAdvice.java
  src/main/java/kr/co/deundeun/groopy/common/dto/ErrorResponseDto.java
  src/main/java/kr/co/deundeun/groopy/config/Me.java
  src/main/java/kr/co/deundeun/groopy/config/security/JwtTokenProvider.java
  src/main/java/kr/co/deundeun/groopy/controller/club/dto/ClubResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/comment/CommentController.java
  src/main/java/kr/co/deundeun/groopy/controller/common/page/PageRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/like/LikeController.java
  src/main/java/kr/co/deundeun/groopy/controller/like/dto/LikeResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/post/PostController.java
  src/main/java/kr/co/deundeun/groopy/controller/post/dto/PostRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/post/dto/PostResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubLikeRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/PostImageRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/PostLikeRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/PostRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/club/Club.java
  src/main/java/kr/co/deundeun/groopy/domain/image/PostImage.java
  src/main/java/kr/co/deundeun/groopy/domain/like/ClubLike.java
  src/main/java/kr/co/deundeun/groopy/domain/like/Likes.java
  src/main/java/kr/co/deundeun/groopy/domain/like/PostLike.java
  src/main/java/kr/co/deundeun/groopy/domain/post/Post.java
  src/main/java/kr/co/deundeun/groopy/domain/user/Anonymous.java
  src/main/java/kr/co/deundeun/groopy/exception/LoginException.java
  src/main/java/kr/co/deundeun/groopy/helper/ClubHelper.java
  src/main/java/kr/co/deundeun/groopy/helper/PostHelper.java
  src/main/java/kr/co/deundeun/groopy/service/ClubService.java
  src/main/java/kr/co/deundeun/groopy/service/CommentService.java
  src/main/java/kr/co/deundeun/groopy/service/LikeService.java
  src/main/java/kr/co/deundeun/groopy/service/PostService.java
Labels: backend, feature

#31 DeunDeun-backend-29 지원하기
  src/main/java/kr/co/deundeun/groopy/common/ErrorCode.java
  src/main/java/kr/co/deundeun/groopy/common/advice/ExceptionAdvice.java
  src/main/java/kr/co/deundeun/groopy/common/dto/ErrorResponseDto.java
  src/main/java/kr/co/deundeun/groopy/config/security/TokenAuthenticationFilter.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/ClubApplyController.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/dto/ApplyAnswerDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/dto/ApplyResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/recruitQuestion/RecruitQuestionController.java
  src/main/java/kr/co/deundeun/groopy/controller/recruitQuestion/dto/RecruitQuestionRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/recruitQuestion/dto/RecruitQuestionResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubRecruitQuestionRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubRecruitRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/club/Club.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApply/ClubApply.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApply/ClubApplyAnswer.java
  src/main/java/kr/co/deundeun/groopy/domain/clubRecruit/ClubRecruit.java
  src/main/java/kr/co/deundeun/groopy/domain/clubRecruit/ClubRecruitQuestion.java
  src/main/java/kr/co/deundeun/groopy/helper/ApplyHelper.java
  src/main/java/kr/co/deundeun/groopy/helper/RecruitHelper.java
  src/main/java/kr/co/deundeun/groopy/service/ClubApplyService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubRecruitService.java
  src/main/java/kr/co/deundeun/groopy/service/RecruitQuestionService.java
Labels: backend, feature

#42 Deun-deun-backend 37,39,40 내 정보 수정
  src/main/java/kr/co/deundeun/groopy/config/security/TokenAuthenticationFilter.java
  src/main/java/kr/co/deundeun/groopy/controller/club/ClubController.java
  src/main/java/kr/co/deundeun/groopy/controller/club/dto/ClubResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/dto/ApplyAnswerDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/dto/ApplyRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/dto/ApplyResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/dto/ApplySummaryResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/like/LikeController.java
  src/main/java/kr/co/deundeun/groopy/controller/like/dto/LikeResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/post/PostController.java
  src/main/java/kr/co/deundeun/groopy/controller/post/dto/PostResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/user/UserController.java
  src/main/java/kr/co/deundeun/groopy/controller/user/dto/LikeListResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/user/dto/SignupRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubLikeRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/ParticipateRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/PostLikeRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/UserClubLikeRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApply/ClubApply.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApply/ClubApplyAnswer.java
  src/main/java/kr/co/deundeun/groopy/domain/user/User.java
  src/main/java/kr/co/deundeun/groopy/helper/LikeHelper.java
  src/main/java/kr/co/deundeun/groopy/service/ClubApplyService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubService.java
  src/main/java/kr/co/deundeun/groopy/service/PostService.java
  src/main/java/kr/co/deundeun/groopy/service/UserService.java
  src/test/java/kr/co/deundeun/groopy/controller/user/UserControllerTest.java
Labels: backend, feature

#46 [FEAT]: 홈화면 첫화면
  src/main/java/kr/co/deundeun/groopy/common/advice/ExceptionAdvice.java
  src/main/java/kr/co/deundeun/groopy/controller/club/dto/ClubResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/common/page/PageRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/common/page/Property.java
  src/main/java/kr/co/deundeun/groopy/controller/home/HomeController.java
  src/main/java/kr/co/deundeun/groopy/controller/home/dto/HomeRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/home/dto/HomeResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/home/dto/PopularClubDto.java
  src/main/java/kr/co/deundeun/groopy/controller/home/dto/PopularPostDto.java
  src/main/java/kr/co/deundeun/groopy/controller/home/dto/RecruitingClubDto.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubRecruitRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/PostRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/club/Club.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApply/ClubApply.java
  src/main/java/kr/co/deundeun/groopy/domain/clubRecruit/ClubRecruit.java
  src/main/java/kr/co/deundeun/groopy/domain/post/Post.java
  src/main/java/kr/co/deundeun/groopy/service/HomeService.java
  src/main/resources/application.yml
  src/test/java/kr/co/deundeun/groopy/controller/user/UserControllerTest.java
  src/test/java/kr/co/deundeun/groopy/controller/user/UserDocumentation.java
Labels: backend, feature

#48 DeunDeun-backend-47 동아리 등록
  build.gradle
  src/main/java/kr/co/deundeun/groopy/config/AppProperties.java
  src/main/java/kr/co/deundeun/groopy/controller/alarm/AlarmController.java
  src/main/java/kr/co/deundeun/groopy/controller/alarm/dto/AlarmRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/alarm/dto/AlarmResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/club/ClubAdminController.java
  src/main/java/kr/co/deundeun/groopy/controller/club/ClubController.java
  src/main/java/kr/co/deundeun/groopy/controller/club/dto/ClubPositionRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/club/dto/ClubResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/common/mail/MailRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dao/AlarmRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubPositionRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/ParticipateRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/alarm/Alarm.java
  src/main/java/kr/co/deundeun/groopy/domain/club/Club.java
  src/main/java/kr/co/deundeun/groopy/domain/user/Participate.java
  src/main/java/kr/co/deundeun/groopy/exception/AuthorizationException.java
  src/main/java/kr/co/deundeun/groopy/service/AlarmService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubAdminService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubRecruitService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubService.java
  src/main/resources/application.yml
Labels: backend, feature

#49 [FEAT]: 동아리 전체, 카테고리 조회
  src/main/java/kr/co/deundeun/groopy/controller/home/HomeController.java
  src/main/java/kr/co/deundeun/groopy/controller/home/dto/ClubByCategoryDto.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/club/Club.java
  src/main/java/kr/co/deundeun/groopy/domain/club/constant/CategoryType.java
  src/main/java/kr/co/deundeun/groopy/domain/hashtag/ClubHashtag.java
  src/main/java/kr/co/deundeun/groopy/domain/user/User.java
  src/main/java/kr/co/deundeun/groopy/service/HomeService.java
Labels: backend, feature

#55 DeunDeun-backend-50 이미지 관리 방식
  src/main/java/kr/co/deundeun/groopy/controller/clubRecruit/dto/RecruitRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubRecruit/dto/RecruitResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/post/dto/PostRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/post/dto/PostResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubRecruitImageRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/PostImageRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/clubRecruit/ClubRecruit.java
  src/main/java/kr/co/deundeun/groopy/domain/image/ClubRecruitImage.java
  src/main/java/kr/co/deundeun/groopy/domain/image/PostImage.java
  src/main/java/kr/co/deundeun/groopy/domain/post/Post.java
  src/main/java/kr/co/deundeun/groopy/service/ClubRecruitService.java
  src/main/java/kr/co/deundeun/groopy/service/PostService.java
Labels: backend, feature, fix, refactor

#57 DeunDeun-backend-56 역할 종류 구현
  src/main/java/kr/co/deundeun/groopy/controller/club/ClubAdminController.java
  src/main/java/kr/co/deundeun/groopy/controller/club/ClubPositionController.java
  src/main/java/kr/co/deundeun/groopy/controller/club/dto/ClubAdminResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/club/dto/ClubPositionResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubPositionRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/ParticipateRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/club/ClubPosition.java
  src/main/java/kr/co/deundeun/groopy/helper/ClubPositionHelper.java
  src/main/java/kr/co/deundeun/groopy/helper/ParticipateHelper.java
  src/main/java/kr/co/deundeun/groopy/service/ClubAdminService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubPositionService.java
Labels: backend, feature

#60 유저 작성 지원서 CRUD 구현
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/ClubApplyController.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/dto/ApplyAnswerDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/dto/ApplyQAResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/dto/ApplyRequestDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/dto/ApplyResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/dto/ApplySummaryResponseDto.java
  src/main/java/kr/co/deundeun/groopy/controller/user/UserController.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApply/ClubApply.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApply/ClubApplyAnswer.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApply/constant/ClubApplyStatus.java
  src/main/java/kr/co/deundeun/groopy/domain/clubRecruit/ClubRecruit.java
  src/main/java/kr/co/deundeun/groopy/helper/ClubApplyHelper.java
  src/main/java/kr/co/deundeun/groopy/helper/ClubRecruitHelper.java
  src/main/java/kr/co/deundeun/groopy/service/ClubApplyService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubRecruitService.java
  src/main/java/kr/co/deundeun/groopy/service/CommentService.java
Labels: backend, fix, refactor

#62 DeunDeun-backend-61 Club 리팩토링
  src/main/java/kr/co/deundeun/groopy/config/WebMvcConfig.java
  src/main/java/kr/co/deundeun/groopy/config/security/GroupInterceptor.java
  src/main/java/kr/co/deundeun/groopy/controller/HashtagController.java
  src/main/java/kr/co/deundeun/groopy/controller/UserController.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubAdminRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubRecruitRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/ParticipateRepository.java
  src/main/java/kr/co/deundeun/groopy/dao/UserClubRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/club/Club.java
  src/main/java/kr/co/deundeun/groopy/domain/club/ClubAdmin.java
  src/main/java/kr/co/deundeun/groopy/domain/club/ClubImage.java
  src/main/java/kr/co/deundeun/groopy/domain/club/ClubPosition.java
  src/main/java/kr/co/deundeun/groopy/domain/clubRecruit/ClubRecruit.java
  src/main/java/kr/co/deundeun/groopy/domain/hashtag/ClubHashtag.java
  src/main/java/kr/co/deundeun/groopy/domain/hashtag/UserHashtag.java
  src/main/java/kr/co/deundeun/groopy/domain/user/Participate.java
  src/main/java/kr/co/deundeun/groopy/domain/user/User.java
  src/main/java/kr/co/deundeun/groopy/dto/club/ClubRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubAdmin/ClubAdminResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubPosition/ClubPositionRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubRecruit/ClubRecruitRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubRecruit/ClubRecruitResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/hashtag/HashtagResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/home/RecruitingClubDto.java
  src/main/java/kr/co/deundeun/groopy/service/ClubAdminService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubPositionService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubRecruitService.java
  src/main/java/kr/co/deundeun/groopy/service/ClubService.java
  src/main/java/kr/co/deundeun/groopy/service/HashtagService.java
  src/main/java/kr/co/deundeun/groopy/service/UserService.java
Labels: backend, feature, fix, refactor

#64 DeunDeun-backend-63 좋아요 경로 수정
  src/main/java/kr/co/deundeun/groopy/controller/ClubController.java
  src/main/java/kr/co/deundeun/groopy/controller/LikeController.java
  src/main/java/kr/co/deundeun/groopy/controller/PostController.java
  src/main/java/kr/co/deundeun/groopy/service/ClubService.java
  src/main/java/kr/co/deundeun/groopy/service/LikeService.java
  src/main/java/kr/co/deundeun/groopy/service/PostService.java
Labels: backend, refactor

#68 DeunDeun-backend-65 동아리 참여 정보
  src/main/java/kr/co/deundeun/groopy/common/advice/ExceptionAdvice.java
  src/main/java/kr/co/deundeun/groopy/controller/ClubAdminController.java
  src/main/java/kr/co/deundeun/groopy/controller/ParticipateController.java
  src/main/java/kr/co/deundeun/groopy/dao/ParticipateRepository.java
  src/main/java/kr/co/deundeun/groopy/dto/participate/ParticipateRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/participate/ParticipateResponseDto.java
  src/main/java/kr/co/deundeun/groopy/service/ClubAdminService.java
  src/main/java/kr/co/deundeun/groopy/service/ParticipateService.java
Labels: backend, feature

#69 DeunDeun-backend-66 동아리 역할
  src/main/java/kr/co/deundeun/groopy/common/advice/ExceptionAdvice.java
  src/main/java/kr/co/deundeun/groopy/controller/ClubPositionController.java
  src/main/java/kr/co/deundeun/groopy/controller/ParticipateController.java
  src/main/java/kr/co/deundeun/groopy/controller/UserController.java
  src/main/java/kr/co/deundeun/groopy/dao/ParticipateRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/club/Club.java
  src/main/java/kr/co/deundeun/groopy/dto/clubPosition/ClubPositionRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubPosition/ClubPositionResponseDto.java
  src/main/java/kr/co/deundeun/groopy/dto/clubPosition/participates/PositionChangeDto.java
  src/main/java/kr/co/deundeun/groopy/dto/like/liked/LikeListResponseDto.java
  src/main/java/kr/co/deundeun/groopy/helper/ParticipateHelper.java
  src/main/java/kr/co/deundeun/groopy/service/ClubPositionService.java
  src/main/java/kr/co/deundeun/groopy/service/ParticipateService.java
  src/main/java/kr/co/deundeun/groopy/service/UserService.java
Labels: backend, feature

#71 DeunDeun-backend-70 지원서 평가
  src/main/java/kr/co/deundeun/groopy/config/SwaggerConfig.java
  src/main/java/kr/co/deundeun/groopy/controller/alarm/AlarmController.java
  src/main/java/kr/co/deundeun/groopy/controller/club/ClubController.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApply/ClubApplyController.java
  src/main/java/kr/co/deundeun/groopy/controller/clubApplyForm/ClubApplyFormController.java
  src/main/java/kr/co/deundeun/groopy/controller/clubPosition/ClubPositionController.java
  src/main/java/kr/co/deundeun/groopy/controller/clubRecruit/ClubRecruitController.java
  src/main/java/kr/co/deundeun/groopy/controller/comment/CommentController.java
  src/main/java/kr/co/deundeun/groopy/controller/evaluation/EvaluationController.java
  src/main/java/kr/co/deundeun/groopy/controller/hashtag/HashtagController.java
  src/main/java/kr/co/deundeun/groopy/controller/home/HomeController.java
  src/main/java/kr/co/deundeun/groopy/controller/image/ImageController.java
  src/main/java/kr/co/deundeun/groopy/controller/jwt/JwtController.java
  src/main/java/kr/co/deundeun/groopy/controller/like/LikeController.java
  src/main/java/kr/co/deundeun/groopy/controller/participate/ParticipateController.java
  src/main/java/kr/co/deundeun/groopy/controller/post/PostController.java
  src/main/java/kr/co/deundeun/groopy/controller/user/UserController.java
  src/main/java/kr/co/deundeun/groopy/dao/ClubApplyRepository.java
  src/main/java/kr/co/deundeun/groopy/domain/clubApply/ClubApply.java
  src/main/java/kr/co/deundeun/groopy/dto/evaluate/ClubApplyStatusDto.java
  src/main/java/kr/co/deundeun/groopy/dto/evaluate/EvaluateRequestDto.java
  src/main/java/kr/co/deundeun/groopy/dto/evaluate/EvaluateResponseDto.java
  src/main/java/kr/co/deundeun/groopy/helper/ClubApplyHelper.java
  src/main/java/kr/co/deundeun/groopy/service/ClubRecruitService.java
  src/main/java/kr/co/deundeun/groopy/service/EvaluateService.java
Labels: backend, feature
